version: "3.3"
services:
  pastec:
    container_name: ${PROJECT_NAME}_pastec
    image: swissartresearx/pastec:latest
    restart: unless-stopped
    volumes:
      - ./pastec-index:/pastec/build/pastec-index

  jobs:
    build: ./services/jobs
    container_name: ${PROJECT_NAME}_jobs
    volumes:
      - ${PWD}/.env:/dotenv/.env
      - ./data:/data
      - ./scripts:/scripts

  api:
    build: ./services/api
    container_name: ${PROJECT_NAME}_api
    ports:
      - 8082:5000
    volumes:
      - ./services/api/src:/src
