# https://taskfile.dev

version: '3'

dotenv:
  - /dotenv/.env

tasks:
  populate-index:
    desc: Populate the Pastec index with image data from  BSO
    cmds:
      - python populateIndex.py --endpoint $SPARQL_ENDPOINT --pastecHost $PASTEC_HOST --pastecPort $PASTEC_PORT --datafile $DATAFILE --logfile $LOGFILE --limit $LIMIT
