# https://taskfile.dev

version: '3'

dotenv:
  - /dotenv/.env

vars:
  INDEX_FILE: /pastec/build/pastec-index/index.dat

tasks:

  generate-rdf-output:
      desc: Generate RDF output based on the results JSON file
      cmds:
        - python generateRDFoutput.py --inputfile $RESULTS_JSON --outputfile $RESULTS_RDF

  load-index:
    desc: Load the index from a file
    cmds:
      - curl -X POST -d '{"type":"LOAD", "index_path":"{{.INDEX_FILE}}"}' "http://$PASTEC_HOST:$PASTEC_PORT/index/io"

  populate-index:
    desc: Populate the Pastec index with image data from  BSO
    cmds:
      - python populateIndex.py --endpoint $SPARQL_ENDPOINT --pastecHost $PASTEC_HOST --pastecPort $PASTEC_PORT --datafile $DATAFILE --logfile $LOGFILE --limit $LIMIT

  retrieve-all-similar-images:
      desc: Query the database for image regions and retrieve all similar images
      cmds:
        - python retrieveAllSimilarImages.py --endpoint $SPARQL_ENDPOINT --pastecHost $PASTEC_HOST --pastecPort $PASTEC_PORT --datafile $DATAFILE --logfile $LOGFILE --outputfile $RESULTS_JSON --limit $LIMIT

  query-image:
    desc: Search for an image in the Pastec index by URL
    cmds:
      - python queryImage.py --endpoint $SPARQL_ENDPOINT --pastecHost $PASTEC_HOST --pastecPort $PASTEC_PORT --datafile $DATAFILE --logfile $LOGFILE --limit $LIMIT --imageUrl {{.CLI_ARGS}}
  
  save-index:
    desc: Save the index to a file
    cmds:
      - curl -X POST -d '{"type":"WRITE", "index_path":"{{.INDEX_FILE}}"}' "http://$PASTEC_HOST:$PASTEC_PORT/index/io"